name: Test Deployment

on:
  push:
    branches:
      - main  # main 브랜치에 코드를 올리면 자동으로 실행

jobs:
  test:
    runs-on: ubuntu-latest  # GitHub에서 테스트를 실행할 운영 체제
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 코드 확인

      - name: Install Dependencies
        run: npm install  # 필요한 라이브러리 설치

      - name: Run Tests
        run: npm test  # 웹사이트 테스트 실행
